#%RAML 1.0 DataType
description: Data type for a raid composition.

properties:
  name:
    type: string
    description: The name of the comp.
    example: "DoubleChrono"
  categories:
    type: string[]
    description: The name of the comp's category.
    example: [ "Generic" ]
  roles:
    type: array
    description: A list of roles that this comp is comprised of.
    items:
      properties:
        name:
          type: string
          description: The name of the role.
          example: "🟣 Chrono"
        requiredParticipants:
          type: number
          description: The max number of participants that can sign up to that role.
          example: 2
        type:
          type: string
          description: The type of the role. "Basic" for static roles.
          example: "DPS"
        listIndex:
          type: number
          description: Used to define mutual exclusivity between special roles. Same list index = mutually exclusive.
          example: 0
          required: false