#%RAML 1.0 DataType
description: Data type for a guild options object.

properties:
  raidUnregisterNotificationTime:
    type: number
    description: The number of hours before a raid during which commanders get notified for unregisters.
    example: 1
  raidReminderNotificationTime:
    type: number
    description: The number of minutes before a raid for participants to be sent reminders.
    example: 60
  autoUnpublishTime:
    type: number
    description: The number of minutes after a raid that it gets unpublished.
    example: 60
  trainingRequestAutoSyncInterval:
    type: number
    description: The number of minutes between training requests getting synced.
    example: 3600
  trainingRequestInactiveDaysBeforeDisable:
    type: number
    description: The number of days that it takes for a training request to expire.
    example: 30
  raidAutoBroadcastTime:
    type: number
    description: The number of minutes during which an open spot in a role can't be broadcast more than once.
    example: 10
  memberRoleId:
    type: string
    description: The ID of the member role.
    example: "732546429645750372"
  guildApplicationsChannelId:
    type: string
    description: The ID of the guild applications channel.
    example: "733078503595180103"
  raidCategoryId:
    type: string
    description: The ID of the raids channel category.
    example: "717131712014057483"
  raidDraftCategoryId:
    type: string
    description: The ID of the raid drafts channel category.
    example: "680874903259316421"
  dbVersion:
    type: number
    description: The version of the database.
    example: 5
  additionalRoleIds:
    type: string[]
    description: Additional roles to be given to a user after they get approved.
    example: [ "725275333141463120" ]
  serverRegion:
    type: string
    description: What GW2 server the guild is in.
    enum: [ "Europe", "North America", "Any" ]
    example: "Europe"
  removeRaidReminderHoursBefore:
    type: number
    description: How many hours after a raid is over does the daily raid removal reminder start being sent.
    example: 36
  roleRequests:
    type: array
    description: Special role requests for each wing.
    items:
      properties:
        wing:
          type: number
          description: The wing that the role request is for.
          example: 2
        request:
          type: string
          description: The name of the special role request
          example: "Tank"
  roleRequestsLimit:
    type: number
    description: The maximum number of role requests a user can have active at any one time.
    example: 3
  wingRoles:
    type: array
    description: What training request role to give to each wing.
    items:
      properties:
        wing:
          type: number
          description: The wing that the role request is for.
          example: 2
        roleId:
          type: string
          description: The Discord ID for the role.
          example: "1181703997963374764"
  arcDpsChannelId:
    type: string
    description: The channel to post ArcDPS updates to.
    example: "1196392589805498458"
  dynamicCompOptions:
    type: object
    description: The names of dynamic comp roles.
    properties:
      genericAlacrity:
        type: string
        description: The name of the generic alacrity dynamic role.
        example: "Alacrity"
      healAlacrity:
        type: string
        description: The name of the heal alacrity dynamic role.
        example: "Heal Alacrity"
      dpsAlacrity:
        type: string
        description: The name of the DPS alacrity dynamic role.
        example: "DPS Alacrity"
      genericQuickness:
        type: string
        description: The name of the generic quickness dynamic role.
        example: "Quickness"
      healQuickness:
        type: string
        description: The name of the heal quickness dynamic role.
        example: "Heal Quickness"
      dpsQuickness:
        type: string
        description: The name of the DPS quickness dynamic role.
        example: "DPS Quickness"
      dps:
        type: string
        description: The name of the DPS dynamic role.
        example: "DPS"
    example: !include ../examples/snippets/dynamiccompoptions-object.json
  feedbackBroadcastTime:
    type: number
    description: The number of minutes after a raid that participants get automatically DM'd with the feedback message.
    example: 15
  feedbackMessage:
    type: string
    description: The feedback message that is sent via DM or pings.
    example: "Thank you for joining! Feel free to leave feedback."
