#%RAML 1.0 DataType
description: Data type for a  event log.

properties:
  raidUnregisterNotificationTime:
    type: number
    description: The number of hours before a raid during which commanders get notified for unregisters.
    example: 1
  raidReminderNotificationTime:
    type: number
    description: The number of minutes before a raid for participants to be sent reminders.
    example: 60
  autoUnpublishTime:
    type: number
    description: The number of minutes after a raid that it gets unpublished.
    example: 60
  trainingRequestAutoSyncInterval:
    type: number
    description: The number of minutes between training requests getting synced.
    example: 3600
  trainingRequestInactiveDaysBeforeDisable:
    type: number
    description: The number of days that it takes for a training request to expire.
    example: 30
  raidAutoBroadcastTime:
    type: number
    description: The number of minutes during which an open spot in a role can't be broadcast more than once.
    example: 10
  memberRoleId:
    type: string
    description: The ID of the member role.
    example: "732546429645750372"
  guildApplicationsChannelId:
    type: string
    description: The ID of the guild applications channel.
    example: "733078503595180103"
  raidCategoryId:
    type: string
    description: The ID of the raids channel category.
    example: "717131712014057483"
  raidDraftCategoryId:
    type: string
    description: The ID of the raid drafts channel category.
    example: "680874903259316421"
  feedbackBroadcastTime:
    type: number
    description: The number of minutes after a raid that participants get automatically DM'd with the feedback message.
    example: 15
  feedbackMessage:
    type: string
    description: The feedback message that is sent via DM or pings.
    example: "Thank you for joining! Feel free to leave feedback."
