#%RAML 1.0 DataType
description: Data type for a  event log.

properties:
  raidUnregisterNotificationTime:
    type: number
    description: The number of hours before a raid during which commanders get notified for unregisters.
    example: 1
  raidReminderNotificationTime:
    type: number
    description: The number of minutes before a raid for participants to be sent reminders.
    example: 60
  trainingRequestAutoSyncInterval:
    type: number
    description: The number of minutes between training requests getting synced.
    example: 3600
  trainingRequestInactiveDaysBeforeDisable:
    type: number
    description: The number of days that it takes for a training request to expire.
    example: 30
  commanderRoles:
    type: array
    description: The list of role IDs of roles that allow invoking of commander commands.
    items: string
    example: ["400792057414811659", "747573522024628366"]
  officerRoles:
    type: array
    description: The list of role IDs of roles that allow invoking of officer commands.
    items: string
    example: ["365835222765273091", "156176400619929600"]
  memberRoleId:
    type: string
    description: The ID of the member role.
    example: "732546429645750372"
  guildApplicationsChannelId:
    type: string
    description: The ID of the guild applications channel.
    example: "733078503595180103"
  raidCategoryId:
    type: string
    description: The ID of the raids channel category.
    example: "717131712014057483"
  raidDraftCategoryId:
    type: string
    description: The ID of the raid drafts channel category.
    example: "680874903259316421"
