#%RAML 1.0 DataType
description: Data type for a raid event log.

properties:
  date:
    type: datetime-only
    description: The date and time that the action described by the log entry happened. In the format yyyy-MM-ddTHH:mm:ss.
    example: "2021-02-04T23:17:54"
  type:
    type: string
    description: The type of log entry that this is.
    example: "Created"
  data:
    type: object
    description: Additional data on the log.
    properties:
      user:
        type: string
        description: The user associated with this log entry.
        example: "Johnny#8288"
      roleName:
        type: string
        required: false
        description: The role associated with this log entry
        example: "🟡 BS"
      isReserve:
        type: boolean
        required: false
        description: Whether or not the role associated with this log entry is a reserve role or not.
        example: true