#%RAML 1.0 DataType
description: Data type for a member.

properties:
  gw2Name:
    type: string
    description: The gw2Name of the member.
    example: "John.5231"
  discordName:
    type: string
    description: The discordName of the member.
    example: "John#1529"
  approver:
    type: string
    description: The discordName of the person approving the member.
    example: Tim#6391
  userId:
    type: string
    description: The Discord ID of the member.
    example: "645169823936151572"
  banned:
    type: boolean
    description: Whether or not the member is banned.
    example: false
