#%RAML 1.0 DataType
description: Data type for a raid.

properties:
  name:
    type: string
    description: The name of the raid.
    example: "Wing 4 Continuation"
  description:
    type: string
    description: The description for the raid.
    example: "This is a continuation of my wing 4 training last week."
  status:
    type: string
    description: Whether the raid is published (currently live), draft (currently unpublished), or archived (removed).
    enum: ["Published", "Draft", "Archived"]
  startTime:
    type: datetime-only
    description: The date and time that the raid is scheduled to start. In the format yyyy-MM-ddTHH:mm:ss.
    example: "2021-01-29T19:00:00"
  endTime:
    type: datetime-only
    description: The date and time that the raid is scheduled to finish. In the format yyyy-MM-ddTHH:mm:ss.
    example: "2021-01-29T22:00:00"
  leader:
    type: string
    description: The Discord name of the leader of the raid.
    example: "Step#1937"
  comp:
    type: string
    description: The name of the comp used for the raid.
    example: "Deimos"
  sendTrainingRequestDM:
    type: boolean
    description: Whether or not to send a training request DM after the raid is over for fulfilling special role requests and wing overrides.
    example: true
  publishedDate:
    type: datetime-only
    description: The date and time that the raid is scheduled to start. In the format yyyy-MM-ddTHH:mm:ss.
    example: "2021-01-31T14:37:21"
  channelId:
    type: string
    description: The Discord channel ID of the raid.
    example: "803230670868578354"
  participants:
    type: array
    items: !include ParticipantsRole.raml
    description: A list of participants who have signed up to the raid, organised by role.
    example: !include ../examples/snippets/participants-role-participants.json
  reserves:
    type: array
    items: !include ParticipantsRole.raml
    description: A list of reserves who have signed up to the raid, organised by role.
    example: !include ../examples/snippets/participants-role-reserves.json
  id:
    type: string
    description: The internal ID of the raid as a 12-byte hexadecimal string.
    example: "6013693f614b415d9c3c7e3d"