#%RAML 1.0 DataType
description: Data type for a training request.

properties:
  discordTag:
    type: string
    description: The discordTag of the member who created this training request. If not specified, then the member is not on the server.
    example: "Robert#5512"
    required: false
  active:
    type: boolean
    description: Whether or not the training request is currently active.
    example: true
  requestedWings:
    type: array
    items:
      type: number
    description: A list of wings that the user requested.
    example: [ 2, 4, 5 ]
  requestedRoles:
    type: array
    items:
      type: object
      properties:
        wing:
          type: number
          description: The wing of the role request.
          example: 2
        request:
          type: string
          description: The name of the role request.
          example: "Tank"
    description: A list of special roles that the user requested.
    example: !include ../examples/snippets/rolerequests-list.json
  comment:
    type: string
    description: The comment that the member included with their training request.
    example: "I would like to join only Dhuum trainings."
  created:
    type: datetime-only
    description: The date and time that the training request was created.
    example: "2020-12-13T16:28:47"
  edited:
    type: datetime-only
    description: The last time that this training request had an update.
    example: "2020-12-27T16:34:35"
  wingOverrides:
    type: number[]
    description: The list of wings that will remain active in the training request due to manual officer tampering.
    example: [ 1, 3, 5 ]
  disabledReason:
    type: string
    description: The reason for the training request becoming inactive.
    enum: [
      "None",
      "Manually by User",
      "Manually by Officer",
      "Fulfilled",
      "API Key Removed",
      "Invalid API Key",
      "No Longer Member",
      "Expired"
    ]
  userId:
    type: string
    description: The Discord ID of the member.
    example: "645169823936151572"
  history:
    type: object
    description: A map where the keys are wing numbers and the values are details on the training request status for that wing.
    properties:
      requested:
        type: datetime-only
        description: The date that the wing was requested.
        required: false
        example: "2021-01-15T20:05:51"
      cleared:
        type: datetime-only
        description: The date that the wing was cleared.
        required: false
        example: "2021-01-15T20:05:51"
  rolesHistory:
    type: object
    description: A map where the keys are wing numbers and the values are details on the training request status for that wing.
    properties:
      requested:
        type: datetime-only
        description: The date that the role was requested.
        required: false
        example: "2021-01-15T20:05:51"
      cleared:
        type: datetime-only
        description: The date that the role was cleared.
        required: false
        example: "2021-01-15T20:05:51"