version: '3.7'

services:
  api:
    image: rtibot-api
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080      
    networks:
      - RTIBot-network-prod
    container_name: RTI-API
networks:
  RTIBot-network-prod:
    external: true