services:
  api:
    image: rtibot-api
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - ./clients:/clients
      - ./Config.json:/app/dist/Config.json
    ports:
      - 8080:8080
    networks:
      - RTIBot-network-prod
    container_name: RTI-API

networks:
  RTIBot-network-prod:
    external: true
