#%RAML 1.0 DataType
title: Comp
description: Data type for a raid composition.

types:
  Role: !include User.dataType.raml

properties:
  name:
    type: string
    description: The name of the comp.
    example: "DoubleChrono"
  category:
    type: string
    description: The name of the comp's category.
    example: "Generic"
  roles:
    type: Role[]
    description: A list of roles that this comp is comprised of.