#%RAML 1.0
title: RTI API
types:
  RaidSummary: !include types/RaidSummary.raml
  Raid: !include types/Raid.raml
  Member: !include types/Member.raml
  Log: !include types/Log.raml
  Comp: !include types/Comp.raml
  Category: !include types/Category.raml
  TrainingRequest: !include types/TrainingRequest.raml
  TrainingRequestSummary: !include types/TrainingRequestSummary.raml
  GuildOptions: !include types/GuildOptions.raml
  Status: !include types/Status.raml
  DiscordAuth: !include types/DiscordAuth.raml
traits:
  requiresAuthentication: !include traits/RequiresAuthentication.raml
  supportsPagination: !include traits/SupportsPagination.raml
  multiFormat: !include traits/multiFormat.raml

/raids:
  get:
    description: Gets a list of the saved raids. Each raid is summarised and certain fields are left out for a cleaner view.
    is: ["requiresAuthentication", "supportsPagination", "multiFormat"]
    queryParameters:
      status:
        type: string
        description: A comma-separated, case-insensitive string to filter the raids by status.
        example: "draft,published,archived"
      name:
        type: string
        description: A case-insensitive string to filter the raids by name. Returns raids whose name contains the filter query string as a substring.
        example: "continuation"
      comps:
        type: string
        description: A comma-separated, case-insensitive string to filter the raids by comp names.
        example: "DoubleChrono,Dhuum-RR"
      leader:
        type: string
        description: A case-insensitive string with all numbers and dots and hashtags removed to filter the raids by leader name.
        example: Step
      published:
        type: boolean
        description: A boolean indicating whether or not to only output published raids.
        example: true
      participants:
        type: string
        description: A comma-separated, case-sensitive string to filter the raids by participants' Discord names. All participants in this query list have to be present as participants in the raid.
        example: "step%230,akronox%230"
      reserves:
        type: string
        description: A comma-separated, case-sensitive string to filter the raids by reserves' Discord names. All reserves in this query list have to be present as reserves in the raid.
        example: "step%230,akronox%230"
    responses:
      200:
        body:
          application/json:
            description: A list of raids in JSON format.
            type: RaidSummary[]
            example: !include examples/responses/json/list-raids.json
          application/csv:
            description: A list of raids in CSV format.
            example: !include examples/responses/csv/list-raids.csv
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/bad-syntax-bad-status.json
      404:
        body:
          application/json:
            description: Error response when the specified leader was not found.
            example: !include examples/errors/resource-not-found.json
  /{id}:
    get:
      description: Gets a single raid.
      is: ["requiresAuthentication"]
      queryParameters:
        names:
          type: string
          description: A case-insensitive string specifying what values the names should be.
          enum: ["gw2", "discord"]
      responses:
        200:
          body:
            application/json:
              description: A raid.
              type: Raid
              example: !include examples/responses/json/get-raid.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/bad-syntax-bad-names.json
        404:
          body:
            application/json:
              description: Error response when the raid ID being requested is not found.
              example: !include examples/errors/resource-not-found.json
    /log:
      get:
        description: Gets the event log of a raid.
        is: ["requiresAuthentication"]
        queryParameters:
          names:
            type: string
            description: A case-insensitive string specifying what values the names should be.
            enum: ["gw2", "discord"]
        responses:
          200:
            body:
              application/json:
                description: A list of raid event logs.
                type: Log[]
          400:
            body:
              application/json:
                description: Error response when syntax is invalid.
                example: !include examples/errors/bad-syntax-bad-names.json
          404:
            body:
              application/json:
                description: Error response when the raid ID being requested is not found.
                example: !include examples/errors/resource-not-found.json

/members:
  get:
    description: Gets a list of the saved members.
    is: ["requiresAuthentication", "supportsPagination", "multiFormat"]
    queryParameters:
      gw2Name:
        type: string
        description: Filter by gw2Name of the member (can be incomplete).
        example: John.5231
      discordTag:
        type: string
        description: Filter by discordTag of the member (can be incomplete). Needs to be URI-safe, so use %23 instead of hashtags!
        example: John%231529
      approver:
        type: string
        description: Filter by the discordTag of the approver of the member.
        example: Tim%236391
      banned:
        type: boolean
        description: Filter by whether or not the member is currently banned.
        example: true
    responses:
      200:
        body:
          application/json:
            description: A list of members in JSON format.
            type: Member[]
            example: !include examples/responses/json/list-members.json
          application/csv:
            description: A list of members in CSV format.
            example: !include examples/responses/csv/list-members.csv
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      404:
        body:
          application/json:
            description: Error response when the approver in the query parameter does not exist.
            example: !include examples/errors/resource-not-found.json
  /{discordid}:
    get:
      description: Gets a single member by their userId.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A member.
              type: Member
              example: !include examples/responses/json/get-member.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json
        404:
          body:
            application/json:
              description: Error response when the member's userId does not exist.
              example: !include examples/errors/resource-not-found.json

/comps:
  get:
    description: Gets a list of the saved raid squad compositions.
    is: ["requiresAuthentication"]
    queryParameters:
      category:
        type: string
        description: A comma-separated, case-insensitive string to filter compositions by categories.
        example: "Generic,Other,Wing%205"
    responses:
      200:
        body:
          application/json:
            description: A list of compositions.
            type: Comp[]
            example: !include examples/responses/json/list-comps.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
  post:
    description: Creates a raid squad composition in the database.
    is: ["requiresAuthentication"]
    body:
      applicaton/json:
        description: The comp to put in the database.
        type: Comp
        example: !include examples/requests/create-comp.json
    responses:
      201:
        body:
          application/json:
            description: The comp that was created in the database.
            type: Comp
            example: !include examples/responses/json/create-comp.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/bad-syntax-bad-json.json
      404:
        body:
          application/json:
            description: Error response when a category in the comp to be created could not be found.
            example: !include examples/errors/resource-not-found.json
      422:
        body:
          application/json:
            description: Error response when the comp to be created already exists.
            example: !include examples/errors/resource-already-exists.json
  /{comp}:
    get:
      description: Gets a single raid squad composition by name.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A composition.
              type: Comp
              example: !include examples/responses/json/get-comp.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested comp could not be found.
              example: !include examples/errors/resource-not-found.json
    delete:
      description: Deletes a single raid squad composition by name.
      is: ["requiresAuthentication"]
      responses:
        204:
          body:
            text/plain: !null
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested comp could not be found.
              example: !include examples/errors/resource-not-found.json

/categories:
  get:
    description: Gets a list of the saved raid squad composition categories.
    is: ["requiresAuthentication"]
    responses:
      200:
        body:
          application/json:
            description: A list of categories.
            type: Category[]
            example: !include examples/responses/json/list-categories.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
  /{category}:
    get:
      description: Gets a single raid squad composition category by name.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A category.
              type: Category
              example: !include examples/responses/json/get-category.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested category could not be found.
              example: !include examples/errors/resource-not-found.json

/trainingrequests:
  get:
    description: Gets a list of the saved training requests.
    is: ["requiresAuthentication", "supportsPagination", "multiFormat"]
    queryParameters:
      users:
        type: string
        description: A comma-separated, case-sensitive string to filter the training requests by users' Discord names.
        example: "Steven%231590,Rick%236631"
      keywords:
        type: string
        description: A comma-separated, case-insensitive list of keywords to search in the comments. Only results that contain all the keywords are returned.
        example: "dhuum,only,dps"
      active:
        type: boolean
        description: A boolean indicating whether or not to only output active training requests.
        example: true
      wings:
        type: string
        description: A comma-separated list of wing numbers to filter the training requests by requested wings.
        example: "4,5,7"
      disabledReasons:
        type: string
        description: A comma-separated, case-insensitive list of disabled reasons to filter the training requests with.
        enum: [
          "None",
          "Manually by User",
          "Manually by Officer",
          "Fulfilled",
          "API Key Removed",
          "Invalid API Key",
          "No Longer Member",
          "Expired"
        ]
    responses:
      200:
        body:
          application/json:
            description: A list of training requests in JSON format.
            type: TrainingRequestSummary[]
            example: !include examples/responses/json/list-training-requests.json
          application/csv:
            description: A list of training requests in CSV format.
            example: !include examples/responses/csv/list-training-requests.csv
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json 
  /{userid}:
    get:
      description: Gets a single training request by the user ID of the member that made it.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A training request.
              type: TrainingRequest
              example: !include examples/responses/json/get-training-request.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested category could not be found.
              example: !include examples/errors/resource-not-found.json

/guildoptions:
  get:
    description: Returns an object specifying the guild option values.
    responses:
      200:
        body:
          application/json:
            description: A guild options object.
            type: GuildOptions
            example: !include examples/responses/json/get-guild-options.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      500:
        body:
          application/json:
            description: Error response when the guild options aren't found in the database.
            example: !include examples/errors/no-guild-options.json

/discordauth:
  post:
    description: Returns the user's info and an access token in exchange for a Discord OAuth2 access code.
    queryParameters:
      code:
        type: string
        description: The code obtained through the Discord OAuth process.
        example: "ARUwr5OIQhy06TCnsGHoRyI6dg3qND"
    responses:
      200:
        body:
          application/json:
            description: A DiscordAuth object.
            type: DiscordAuth
            example: !include examples/responses/json/post-discordauth.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      440:
        body:
          application/json:
            description: Error response when the session associated with this token has expired and the user must authenticate again.
            example: !include examples/errors/session-expired.json
      500:
        body:
          application/json:
            description: Error response when an internal error occurs, most likely because the Discord API call failed.
            example: !include examples/errors/server-error.json

/status:
  get:
    description: Returns an object providing details on the API.
    responses:
      200:
        body:
          application/json:
            description: A status object.
            type: Status
            example: !include examples/responses/json/get-status.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      500:
        body:
          application/json:
            description: Error response when package.json file could not be found.
            example: !include examples/errors/package-json-not-found.json

/stats:
  get:
    description: Returns an object providing statistics about the data.
    responses:
      200:
        body:
          application/json:
            description: An object with statistics about the data.
            example: !include examples/responses/json/get-stats.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json