#%RAML 1.0
title: RTI API
types:
  RaidSummary: !include types/RaidSummary.raml
  Raid: !include types/Raid.raml
  Member: !include types/Member.raml
  Log: !include types/Log.raml
  Comp: !include types/Comp.raml
  Category: !include types/Category.raml
  Status: !include types/Status.raml
traits:
  requiresAuthentication:
    headers:
      Authorization:
        description: Basic authentication with a 64-character client secret.
        type: string
        required: true
        example: "Basic 22AB6BsFYJgqqclNbknmUr7gG0nn5qtiXgdxJP7G0dTnkUjSN5nZNFca3M8Wfe3k"
    responses:
      401:
        body:
          application/json:
            description: Error response when authentication failed.
            example: !include examples/errors/unauthorized.json
  supportsPagination:
    queryParameters:
      page:
        type: number
        description: A number greater than 0 indicating what page of results to return.
        example: 4
      pageSize:
        type: number
        description: A number greater than 0 indicating how many results to return per page.
        example: 20

/raids:
  get:
    description: Gets a list of the saved raids. Each raid is summarised and certain fields are left out for a cleaner view.
    is: ["requiresAuthentication", "supportsPagination"]
    queryParameters:
      status:
        type: string
        description: A case-insensitive string to filter the raids by status.
        enum: ["Published", "Draft", "Archived"]
      name:
        type: string
        description: A case-insensitive string to filter the raids by name. Returns raids whose name contains the filter query string as a substring.
        example: "continuation"
      comp:
        type: string
        description: A case-insensitive string to filter the raids by comp name.
        example: "DoubleChrono"
      leader:
        type: string
        description: A case-insensitive string with all numbers and dots and hashtags removed to filter the raids by leader name.
        example: Step
      published:
        type: boolean
        description: A boolean indicating whether or not to only output published raids.
        example: true
      format:
        type: string
        description: A case-insensitive string to define whether to return a JSON or CSV response.
        enum: ["csv", "json"]

    responses:
      200:
        body:
          application/json:
            description: A list of raids in JSON format.
            type: RaidSummary[]
            example: !include examples/responses/list-raids.json
          application/csv:
            description: A list of raids in CSV format.
            example: !include examples/responses/list-raids.csv
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/bad-syntax-bad-status.json
  /{id}:
    get:
      description: Gets a single raid.
      is: ["requiresAuthentication"]
      queryParameters:
        names:
          type: string
          description: A case-insensitive string specifying what values the names should be.
          enum: ["gw2", "discord"]
      responses:
        200:
          body:
            application/json:
              description: A raid.
              type: Raid
              example: !include examples/responses/get-raid.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/bad-syntax-bad-names.json
        404:
          body:
            application/json:
              description: Error response when the raid ID being requested is not found.
              example: !include examples/errors/resource-not-found.json
    /log:
      get:
        description: Gets the event log of a raid.
        is: ["requiresAuthentication"]
        queryParameters:
          names:
            type: string
            description: A case-insensitive string specifying what values the names should be.
            enum: ["gw2", "discord"]
        responses:
          200:
            body:
              application/json:
                description: A list of raid event logs.
                type: Log[]
          400:
            body:
              application/json:
                description: Error response when syntax is invalid.
                example: !include examples/errors/bad-syntax-bad-names.json
          404:
            body:
              application/json:
                description: Error response when the raid ID being requested is not found.
                example: !include examples/errors/resource-not-found.json

/members:
  get:
    description: Gets a list of the saved members.
    is: ["requiresAuthentication", "supportsPagination"]
    queryParameters:
      gw2Name:
        type: string
        description: Filter by gw2Name of the member (can be incomplete).
        example: John.5231
      discordName:
        type: string
        description: Filter by discordName of the member (can be incomplete).
        example: John#1529
      approver:
        type: string
        description: Filter by the discordName of the approver of the member.
        example: Tim#6391
    responses:
      200:
        body:
          application/json:
            description: A list of members.
            type: Member[]
            example: !include examples/responses/list-members.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      404:
        body:
          application/json:
            description: Error response when the approver in the query parameter does not exist.
            example: !include examples/errors/resource-not-found.json
  /{discordid}:
    get:
      description: Gets a single member by their userId.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A member.
              type: Member
              example: !include examples/responses/get-member.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json
        404:
          body:
            application/json:
              description: Error response when the member's userId does not exist.
              example: !include examples/errors/resource-not-found.json

/comps:
  get:
    description: Gets a list of the saved raid squad compositions.
    is: ["requiresAuthentication"]
    queryParameters:
      category:
        type: string
        description: A URI-safe, comma-separated list of composition categories
        example: "Generic,Other,Wing%205"
    responses:
      200:
        body:
          application/json:
            description: A list of compositions.
            type: Comp[]
            example: !include examples/responses/list-comps.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
  /{comp}:
    get:
      description: Gets a single raid squad composition by name.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A composition.
              type: Comp
              example: !include examples/responses/get-comp.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested comp could not be found.
              example: !include examples/errors/resource-not-found.json

/categories:
  get:
    description: Gets a list of the saved raid squad composition categories.
    is: ["requiresAuthentication"]
    responses:
      200:
        body:
          application/json:
            description: A list of categories.
            type: Category[]
            example: !include examples/responses/list-categories.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
  /{category}:
    get:
      description: Gets a single raid squad composition category by name.
      is: ["requiresAuthentication"]
      responses:
        200:
          body:
            application/json:
              description: A category.
              type: Category
              example: !include examples/responses/get-category.json
        400:
          body:
            application/json:
              description: Error response when syntax is invalid.
              example: !include examples/errors/invalid-query-parameters.json 
        404:
          body:
            application/json:
              description: Error response when the requested category could not be found.
              example: !include examples/errors/resource-not-found.json

/status:
  get:
    description: Returns an object providing details on the API.
    responses:
      200:
        body:
          application/json:
            description: A status object.
            type: Status
            example: !include examples/responses/get-status.json
      400:
        body:
          application/json:
            description: Error response when syntax is invalid.
            example: !include examples/errors/invalid-query-parameters.json
      500:
        body:
          application/json:
            description: Error response when package.json file could not be found.
            example: !include examples/errors/package-json-not-found.json