#%RAML 1.0 Trait

queryParameters:
  page:
    type: number
    description: A number greater than 0 indicating what page of results to return.
    example: 4
  pageSize:
    type: number
    description: A number greater than 0 indicating how many results to return per page.
    example: 20